version: "2017-09-20"
pipeline:

- id: build
  overlay: ci/golang-1-11
  type: script
  working_dir: /go/src/k8s.io/autoscaler
  vm: large
  env:
    VERSION: "v1.14.5-internal"
    DOWNSTREAM: "registry-write.opensource.zalan.do/teapot/kube-cluster-autoscaler"
  commands:
  - desc: "Installing dependencies"
    cmd: |
      apt-get update
      apt-get install libseccomp-dev -qq
      hack/install-verify-tools.sh
      go version
      export PATH=$GOPATH/bin:$PATH
  - desc: "Verify"
    cmd: |
      rm .zappr.yaml
      hack/verify-all.sh -v
  - desc: "Build and release"
    cmd: |
      if [[ "${CDP_TARGET_BRANCH}" != "zalando-cluster-autoscaler" || -n "${CDP_PULL_REQUEST_NUMBER}" ]]; then
        VERSION="${VERSION}.dev-${CDP_TARGET_REPOSITORY_COUNTER}"
      else
        VERSION="${VERSION}.${CDP_TARGET_BRANCH_COUNTER}"
      fi

      cd cluster-autoscaler
      make test-in-docker
      make build-in-docker

      IMAGE="${DOWNSTREAM}:${VERSION}"
      docker build -t "${IMAGE}" .
      docker push "${IMAGE}"
