version: "2017-09-20"
pipeline:
  - id: build
    type: script
    vm_config:
      type: linux
      size: large
      image: cdp-runtime/go-1.19
    working_dir: /go/src/k8s.io/autoscaler
    env:
      VERSION: "v0.12.0-internal"
    commands:
      - desc: "Installing dependencies"
        cmd: |
          export GO111MODULE=auto
          hack/install-verify-tools.sh
      - desc: "Verify"
        cmd: |
          rm .zappr.yaml
          export GO111MODULE=auto
          hack/verify-all.sh -v
      - desc: "Build and release"
        cmd: |
          if [[ "${CDP_TARGET_BRANCH}" != "zalando-vertical-pod-autoscaler" || -n "${CDP_PULL_REQUEST_NUMBER}" ]]; then
            export TAG="${VERSION}.dev-${CDP_TARGET_REPOSITORY_COUNTER}"
          else
            export TAG="${VERSION}.${CDP_TARGET_BRANCH_COUNTER}"
          fi

          export ALL_ARCHITECTURES="amd64 arm64"
          docker buildx create --config /etc/cdp-buildkitd.toml --driver-opt network=host --use
          for COMPONENT in admission-controller recommender updater; do
            (
              cd vertical-pod-autoscaler/pkg/$COMPONENT
              make test-unit
              make build-in-docker
              docker buildx build --rm -t container-registry-test.zalando.net/teapot/vpa-${COMPONENT}:${TAG} --platform linux/amd64,linux/arm64 --push .
              cdp-promote-image container-registry-test.zalando.net/teapot/vpa-${COMPONENT}:${TAG}
            )
          done
